# Generated by Django 5.0.6 on 2024-05-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='rooms',
            new_name='room',
        ),
    ]
