# Generated by Django 5.0.6 on 2024-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_rename_rooms_score_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.CharField(default='IT', max_length=100),
            preserve_default=False,
        ),
    ]
