# Generated by Django 5.0.6 on 2024-05-20 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0003_score_subject'),
        ('semester', '0002_semester_rooms_alter_semester_name'),
        ('students', '0002_rename_schoolclass_student_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('subject', 'student', 'semester', 'room')},
        ),
    ]
