# Generated by Django 5.0.6 on 2024-05-20 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_alter_score_score_alter_score_unique_together'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='subject.subject'),
        ),
    ]
