version: '3.8'
services:
  dev-database:
    image: postgres:15.0
    container_name: "hello"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres