# Generated by Django 5.0.6 on 2024-05-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_semester_rooms_alter_semester_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='rooms',
        ),
    ]
