# Generated by Django 5.0.6 on 2024-05-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0003_remove_semester_rooms'),
        ('students', '0003_remove_student_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='semesters',
            field=models.ManyToManyField(related_name='rooms', to='semester.semester'),
        ),
    ]
