# Generated by Django 5.0.6 on 2024-05-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0003_remove_semester_rooms'),
        ('students', '0004_schoolclass_semesters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='semesters',
            field=models.ManyToManyField(default=[], null=True, related_name='rooms', to='semester.semester'),
        ),
    ]
